# THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.
# BASED ON c:\Users\Jonathan\Desktop\Projects\Motorz\03_300W Integrated Motor Inverter\02_Firmware\Motor Firmware\Motor 1\gen4_motor_inverter_NoSVPWM

function(add_st_target_properties TARGET_NAME)

target_compile_definitions(
    ${TARGET_NAME} PRIVATE
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:ASM>>:DEBUG>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:DEBUG>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:USE_HAL_DRIVER>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:STM32G431xx>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:USE_HAL_DRIVER>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:STM32G431xx>"
)

target_include_directories(
    ${TARGET_NAME} PRIVATE
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:C:\\Users\\Jonathan\\Desktop\\Projects\\Motorz\\03_300W Integrated Motor Inverter\\02_Firmware\\Motor Firmware\\Motor 1\\gen4_motor_inverter_NoSVPWM\\Drivers\\Eeprom>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Core\\Inc>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Core/Inc>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers/Ramp>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers/sixSector>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers/EncoderCalibration>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers/AS5x47PS>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\STM32G4xx_HAL_Driver\\Inc>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\STM32G4xx_HAL_Driver\\Inc\\Legacy>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\CMSIS\\Device\\ST\\STM32G4xx\\Include>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\CMSIS\\Include>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers/SVPWM>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers/Q15_math>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Core\\Inc>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\STM32G4xx_HAL_Driver\\Inc>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\STM32G4xx_HAL_Driver\\Inc\\Legacy>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\CMSIS\\Device\\ST\\STM32G4xx\\Include>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\CMSIS\\Include>"
)

target_compile_options(
    ${TARGET_NAME} PRIVATE
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:ASM>>:-g3>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:-g3>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:-g3>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:ASM>>:-g0>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:-g0>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:-g0>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:-Os>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:-Os>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:>"
    "$<$<CONFIG:Debug>:-mcpu=cortex-m4>"
    "$<$<CONFIG:Debug>:-mfpu=fpv4-sp-d16>"
    "$<$<CONFIG:Debug>:-mfloat-abi=hard>"
    "$<$<NOT:$<CONFIG:Debug>>:-mcpu=cortex-m4>"
    "$<$<NOT:$<CONFIG:Debug>>:-mfpu=fpv4-sp-d16>"
    "$<$<NOT:$<CONFIG:Debug>>:-mfloat-abi=hard>"
)

target_link_libraries(
    ${TARGET_NAME} PRIVATE
)

target_link_directories(
    ${TARGET_NAME} PRIVATE
)

target_link_options(
    ${TARGET_NAME} PRIVATE
    "$<$<CONFIG:Debug>:-mcpu=cortex-m4>"
    "$<$<CONFIG:Debug>:-mfpu=fpv4-sp-d16>"
    "$<$<CONFIG:Debug>:-mfloat-abi=hard>"
    "$<$<NOT:$<CONFIG:Debug>>:-mcpu=cortex-m4>"
    "$<$<NOT:$<CONFIG:Debug>>:-mfpu=fpv4-sp-d16>"
    "$<$<NOT:$<CONFIG:Debug>>:-mfloat-abi=hard>"
    -T
    "$<$<CONFIG:Debug>:${PROJECT_SOURCE_DIR}/STM32G431CBTX_FLASH.ld>"
    "$<$<NOT:$<CONFIG:Debug>>:${PROJECT_SOURCE_DIR}/STM32G431CBTX_FLASH.ld>"
)

target_sources(
    ${TARGET_NAME} PRIVATE
    "Core\\Src\\main.c"
    "Core\\Src\\runtime.c"
    "Core\\Src\\stm32g4xx_hal_msp.c"
    "Core\\Src\\stm32g4xx_it.c"
    "Core\\Src\\syscalls.c"
    "Core\\Src\\sysmem.c"
    "Core\\Src\\system_stm32g4xx.c"
    "Core\\Startup\\startup_stm32g431cbtx.s"
    "Drivers\\AS5x47PS\\AS5x47P.c"
    "Drivers\\Eeprom\\Eeprom.c"
    "Drivers\\Eeprom\\EepromFns.c"
    "Drivers\\EncoderCalibration\\EncoderCalibration.c"
    "Drivers\\EncoderSpeed\\EncoderSpeed.c"
    "Drivers\\FDCAN\\FDCAN.c"
    "Drivers\\Q15_math\\libmathq15.c"
    "Drivers\\Ramp\\Ramp.c"
    "Drivers\\sixSector\\sixSector.c"
    "Drivers\\STM32G4xx_HAL_Driver\\Src\\stm32g4xx_hal_adc_ex.c"
    "Drivers\\STM32G4xx_HAL_Driver\\Src\\stm32g4xx_hal_adc.c"
    "Drivers\\STM32G4xx_HAL_Driver\\Src\\stm32g4xx_hal_comp.c"
    "Drivers\\STM32G4xx_HAL_Driver\\Src\\stm32g4xx_hal_cortex.c"
    "Drivers\\STM32G4xx_HAL_Driver\\Src\\stm32g4xx_hal_dac_ex.c"
    "Drivers\\STM32G4xx_HAL_Driver\\Src\\stm32g4xx_hal_dac.c"
    "Drivers\\STM32G4xx_HAL_Driver\\Src\\stm32g4xx_hal_dma_ex.c"
    "Drivers\\STM32G4xx_HAL_Driver\\Src\\stm32g4xx_hal_dma.c"
    "Drivers\\STM32G4xx_HAL_Driver\\Src\\stm32g4xx_hal_exti.c"
    "Drivers\\STM32G4xx_HAL_Driver\\Src\\stm32g4xx_hal_fdcan.c"
    "Drivers\\STM32G4xx_HAL_Driver\\Src\\stm32g4xx_hal_flash_ex.c"
    "Drivers\\STM32G4xx_HAL_Driver\\Src\\stm32g4xx_hal_flash_ramfunc.c"
    "Drivers\\STM32G4xx_HAL_Driver\\Src\\stm32g4xx_hal_flash.c"
    "Drivers\\STM32G4xx_HAL_Driver\\Src\\stm32g4xx_hal_gpio.c"
    "Drivers\\STM32G4xx_HAL_Driver\\Src\\stm32g4xx_hal_i2c_ex.c"
    "Drivers\\STM32G4xx_HAL_Driver\\Src\\stm32g4xx_hal_i2c.c"
    "Drivers\\STM32G4xx_HAL_Driver\\Src\\stm32g4xx_hal_pwr_ex.c"
    "Drivers\\STM32G4xx_HAL_Driver\\Src\\stm32g4xx_hal_pwr.c"
    "Drivers\\STM32G4xx_HAL_Driver\\Src\\stm32g4xx_hal_rcc_ex.c"
    "Drivers\\STM32G4xx_HAL_Driver\\Src\\stm32g4xx_hal_rcc.c"
    "Drivers\\STM32G4xx_HAL_Driver\\Src\\stm32g4xx_hal_spi_ex.c"
    "Drivers\\STM32G4xx_HAL_Driver\\Src\\stm32g4xx_hal_spi.c"
    "Drivers\\STM32G4xx_HAL_Driver\\Src\\stm32g4xx_hal_tim_ex.c"
    "Drivers\\STM32G4xx_HAL_Driver\\Src\\stm32g4xx_hal_tim.c"
    "Drivers\\STM32G4xx_HAL_Driver\\Src\\stm32g4xx_hal.c"
    "Drivers\\STM32G4xx_HAL_Driver\\Src\\stm32g4xx_ll_adc.c"
    "Drivers\\SVPWM\\SVPWM.c"
    "Drivers\\Temperature\\temperatureLUT.c"
    "gen4_motor_inverter_NoSVPWM\\Core\\Src\\main.c"
    "gen4_motor_inverter_NoSVPWM\\Core\\Src\\runtime.c"
    "gen4_motor_inverter_NoSVPWM\\Core\\Src\\stm32g4xx_hal_msp.c"
    "gen4_motor_inverter_NoSVPWM\\Core\\Src\\stm32g4xx_it.c"
    "gen4_motor_inverter_NoSVPWM\\Core\\Src\\syscalls.c"
    "gen4_motor_inverter_NoSVPWM\\Core\\Src\\sysmem.c"
    "gen4_motor_inverter_NoSVPWM\\Core\\Src\\system_stm32g4xx.c"
    "gen4_motor_inverter_NoSVPWM\\Core\\Startup\\startup_stm32g431cbtx.s"
    "gen4_motor_inverter_NoSVPWM\\Drivers\\AS5x47PS\\AS5x47P.c"
    "gen4_motor_inverter_NoSVPWM\\Drivers\\EncoderCalibration\\EncoderCalibration.c"
    "gen4_motor_inverter_NoSVPWM\\Drivers\\EncoderSpeed\\EncoderSpeed.c"
    "gen4_motor_inverter_NoSVPWM\\Drivers\\FDCAN\\FDCAN.c"
    "gen4_motor_inverter_NoSVPWM\\Drivers\\Q15_math\\libmathq15.c"
    "gen4_motor_inverter_NoSVPWM\\Drivers\\Ramp\\Ramp.c"
    "gen4_motor_inverter_NoSVPWM\\Drivers\\sixSector\\sixSector.c"
    "gen4_motor_inverter_NoSVPWM\\Drivers\\STM32G4xx_HAL_Driver\\Src\\stm32g4xx_hal_adc_ex.c"
    "gen4_motor_inverter_NoSVPWM\\Drivers\\STM32G4xx_HAL_Driver\\Src\\stm32g4xx_hal_adc.c"
    "gen4_motor_inverter_NoSVPWM\\Drivers\\STM32G4xx_HAL_Driver\\Src\\stm32g4xx_hal_comp.c"
    "gen4_motor_inverter_NoSVPWM\\Drivers\\STM32G4xx_HAL_Driver\\Src\\stm32g4xx_hal_cortex.c"
    "gen4_motor_inverter_NoSVPWM\\Drivers\\STM32G4xx_HAL_Driver\\Src\\stm32g4xx_hal_dac_ex.c"
    "gen4_motor_inverter_NoSVPWM\\Drivers\\STM32G4xx_HAL_Driver\\Src\\stm32g4xx_hal_dac.c"
    "gen4_motor_inverter_NoSVPWM\\Drivers\\STM32G4xx_HAL_Driver\\Src\\stm32g4xx_hal_dma_ex.c"
    "gen4_motor_inverter_NoSVPWM\\Drivers\\STM32G4xx_HAL_Driver\\Src\\stm32g4xx_hal_dma.c"
    "gen4_motor_inverter_NoSVPWM\\Drivers\\STM32G4xx_HAL_Driver\\Src\\stm32g4xx_hal_exti.c"
    "gen4_motor_inverter_NoSVPWM\\Drivers\\STM32G4xx_HAL_Driver\\Src\\stm32g4xx_hal_fdcan.c"
    "gen4_motor_inverter_NoSVPWM\\Drivers\\STM32G4xx_HAL_Driver\\Src\\stm32g4xx_hal_flash_ex.c"
    "gen4_motor_inverter_NoSVPWM\\Drivers\\STM32G4xx_HAL_Driver\\Src\\stm32g4xx_hal_flash_ramfunc.c"
    "gen4_motor_inverter_NoSVPWM\\Drivers\\STM32G4xx_HAL_Driver\\Src\\stm32g4xx_hal_flash.c"
    "gen4_motor_inverter_NoSVPWM\\Drivers\\STM32G4xx_HAL_Driver\\Src\\stm32g4xx_hal_gpio.c"
    "gen4_motor_inverter_NoSVPWM\\Drivers\\STM32G4xx_HAL_Driver\\Src\\stm32g4xx_hal_i2c_ex.c"
    "gen4_motor_inverter_NoSVPWM\\Drivers\\STM32G4xx_HAL_Driver\\Src\\stm32g4xx_hal_i2c.c"
    "gen4_motor_inverter_NoSVPWM\\Drivers\\STM32G4xx_HAL_Driver\\Src\\stm32g4xx_hal_pwr_ex.c"
    "gen4_motor_inverter_NoSVPWM\\Drivers\\STM32G4xx_HAL_Driver\\Src\\stm32g4xx_hal_pwr.c"
    "gen4_motor_inverter_NoSVPWM\\Drivers\\STM32G4xx_HAL_Driver\\Src\\stm32g4xx_hal_rcc_ex.c"
    "gen4_motor_inverter_NoSVPWM\\Drivers\\STM32G4xx_HAL_Driver\\Src\\stm32g4xx_hal_rcc.c"
    "gen4_motor_inverter_NoSVPWM\\Drivers\\STM32G4xx_HAL_Driver\\Src\\stm32g4xx_hal_spi_ex.c"
    "gen4_motor_inverter_NoSVPWM\\Drivers\\STM32G4xx_HAL_Driver\\Src\\stm32g4xx_hal_spi.c"
    "gen4_motor_inverter_NoSVPWM\\Drivers\\STM32G4xx_HAL_Driver\\Src\\stm32g4xx_hal_tim_ex.c"
    "gen4_motor_inverter_NoSVPWM\\Drivers\\STM32G4xx_HAL_Driver\\Src\\stm32g4xx_hal_tim.c"
    "gen4_motor_inverter_NoSVPWM\\Drivers\\STM32G4xx_HAL_Driver\\Src\\stm32g4xx_hal.c"
    "gen4_motor_inverter_NoSVPWM\\Drivers\\STM32G4xx_HAL_Driver\\Src\\stm32g4xx_ll_adc.c"
    "gen4_motor_inverter_NoSVPWM\\Drivers\\SVPWM\\SVPWM.c"
    "gen4_motor_inverter_NoSVPWM\\Drivers\\Temperature\\temperatureLUT.c"
)

add_custom_command(
    TARGET ${TARGET_NAME} POST_BUILD
    COMMAND ${CMAKE_SIZE} $<TARGET_FILE:${TARGET_NAME}>
)

add_custom_command(
    TARGET ${TARGET_NAME} POST_BUILD
    COMMAND ${CMAKE_OBJCOPY} -O ihex
    $<TARGET_FILE:${TARGET_NAME}> ${TARGET_NAME}.hex
)

add_custom_command(
    TARGET ${TARGET_NAME} POST_BUILD
    COMMAND ${CMAKE_OBJCOPY} -O binary
    $<TARGET_FILE:${TARGET_NAME}> ${TARGET_NAME}.bin
)

endfunction()